-- =============================================================================
-- Migration: Add Stations View and Analytic Tables
-- Date: 2026-06-02
-- =============================================================================

-- 1. Create view for stations with their latest snapshot
CREATE OR REPLACE VIEW public.stations_with_latest_snapshot AS
WITH latest_snaps AS (
    SELECT DISTINCT ON (station_id)
        station_id,
        timestamp,
        bikes,
        docks,
        disabled
    FROM public.snapshots
    ORDER BY station_id, timestamp DESC
)
SELECT 
    s.id,
    s.name,
    s.short_name,
    s.lat,
    s.lon,
    s.capacity,
    s.address,
    s.region,
    snap.bikes,
    snap.docks,
    snap.disabled,
    snap.timestamp AS last_reported
FROM public.stations s
LEFT JOIN latest_snaps snap ON s.id = snap.station_id;

-- 2. Create Analytics Centrality Results Table
CREATE TABLE IF NOT EXISTS public.analytics_centrality_results (
    station_id TEXT PRIMARY KEY REFERENCES public.stations(id) ON DELETE CASCADE,
    name TEXT,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    centrality_index DOUBLE PRECISION,
    centrality_score DOUBLE PRECISION,
    is_critical BOOLEAN,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Create Analytics LISA Results Table
CREATE TABLE IF NOT EXISTS public.analytics_lisa_results (
    station_id TEXT PRIMARY KEY REFERENCES public.stations(id) ON DELETE CASCADE,
    name TEXT,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    cluster_type INTEGER,
    cluster_label TEXT,
    p_value DOUBLE PRECISION,
    availability_ratio DOUBLE PRECISION,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 4. Create Analytics Urban Metabolism Table
CREATE TABLE IF NOT EXISTS public.analytics_urban_metabolism (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_window TEXT NOT NULL,
    station_id TEXT NOT NULL REFERENCES public.stations(id) ON DELETE CASCADE,
    name TEXT,
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    net_flow INTEGER,
    urban_role TEXT,
    updated_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT uq_metabolism_window_station UNIQUE (time_window, station_id)
);

-- 5. Create Analytics Desire Lines Table
CREATE TABLE IF NOT EXISTS public.analytics_desire_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_station_id TEXT NOT NULL REFERENCES public.stations(id) ON DELETE CASCADE,
    end_station_id TEXT NOT NULL REFERENCES public.stations(id) ON DELETE CASCADE,
    start_name TEXT,
    end_name TEXT,
    start_lat DOUBLE PRECISION,
    start_lon DOUBLE PRECISION,
    end_lat DOUBLE PRECISION,
    end_lon DOUBLE PRECISION,
    trip_volume INTEGER,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 6. Create Analytics Multimodal Stress Table
CREATE TABLE IF NOT EXISTS public.analytics_multimodal_stress (
    station_id TEXT PRIMARY KEY REFERENCES public.stations(id) ON DELETE CASCADE,
    volatility_index DOUBLE PRECISION,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 7. Create Analytics Bike Derby Table
CREATE TABLE IF NOT EXISTS public.analytics_bike_derby (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin TEXT,
    destination TEXT,
    start_lat DOUBLE PRECISION,
    start_lon DOUBLE PRECISION,
    end_lat DOUBLE PRECISION,
    end_lon DOUBLE PRECISION,
    dist_km DOUBLE PRECISION,
    inferred_speed_kmh DOUBLE PRECISION,
    volume INTEGER,
    category TEXT,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- 8. Enable Row Level Security (RLS) on all tables
ALTER TABLE public.snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_centrality_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_lisa_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_urban_metabolism ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_desire_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_multimodal_stress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_bike_derby ENABLE ROW LEVEL SECURITY;

-- 9. Create public SELECT policies for all tables
CREATE POLICY "Public select for snapshots" ON public.snapshots FOR SELECT USING (true);
CREATE POLICY "Public select for analytics_centrality_results" ON public.analytics_centrality_results FOR SELECT USING (true);
CREATE POLICY "Public select for analytics_lisa_results" ON public.analytics_lisa_results FOR SELECT USING (true);
CREATE POLICY "Public select for analytics_urban_metabolism" ON public.analytics_urban_metabolism FOR SELECT USING (true);
CREATE POLICY "Public select for analytics_desire_lines" ON public.analytics_desire_lines FOR SELECT USING (true);
CREATE POLICY "Public select for analytics_multimodal_stress" ON public.analytics_multimodal_stress FOR SELECT USING (true);
CREATE POLICY "Public select for analytics_bike_derby" ON public.analytics_bike_derby FOR SELECT USING (true);
