-- =============================================================================
-- Supabase Schema Proposal
-- Run this in your Supabase SQL Editor
-- =============================================================================

-- Enable PostGIS extension (Supabase supports this out of the box)
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. Stations Table
CREATE TABLE IF NOT EXISTS stations (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    short_name TEXT DEFAULT '',
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    capacity INTEGER DEFAULT 0,
    address TEXT DEFAULT '',
    post_code TEXT DEFAULT '',
    region TEXT DEFAULT '',
    geom GEOMETRY(POINT, 4326)
);

-- 2. Snapshots Table (Diffs will be appended here)
CREATE TABLE IF NOT EXISTS snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id TEXT NOT NULL REFERENCES stations(id),
    timestamp TIMESTAMPTZ NOT NULL,
    bikes INTEGER DEFAULT 0,
    docks INTEGER DEFAULT 0,
    disabled INTEGER DEFAULT 0,
    is_renting BOOLEAN DEFAULT TRUE,
    is_returning BOOLEAN DEFAULT TRUE
);

-- Indexes for snapshots
CREATE INDEX IF NOT EXISTS ix_snapshots_station_timestamp ON snapshots (station_id, timestamp);

-- 3. Events Table (For data-art analytics)
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    station_id TEXT NOT NULL REFERENCES stations(id),
    timestamp TIMESTAMPTZ NOT NULL,
    event_type TEXT NOT NULL,
    delta INTEGER DEFAULT 1,
    zone TEXT DEFAULT ''
);

-- Indexes for events
CREATE INDEX IF NOT EXISTS ix_events_timestamp_type ON events (timestamp, event_type);
